alertmanager:
  enabled: true

grafana:
  defaultDashboardsTimezone: Asia/Seoul
  adminPassword: admin1234
  additionalDataSources:
    - name: Thanos
      type: prometheus
      access: proxy
      url: http://thanos-query.monitoring.svc.cluster.local:9090
      isDefault: false
      editable: true

prometheus:
  thanosService:
    enabled: true

  prometheusSpec:
    replicas: 1       # 로컬 테스트용으로 replica 수를 1로 줄임
    retention: 5d
    retentionSize: "10GiB"
    scrapeInterval: "15s"

    thanos:
      image: "quay.io/thanos/thanos:v0.24.0"
      objectStorageConfig:
        existingSecret:
          name: thanos-minio-secret
          key: minio-key.yaml
      version: v0.24.0
    additionalScrapeConfigs:
      - job_name: 'minio-metrics'
        metrics_path: /minio/v2/metrics/cluster
        static_configs:
          - targets: ['minio.minio.svc.cluster.local:9000']
