kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: monitoring-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.29.7
    extraPortMappings:
      - containerPort: 32000   # Grafana의 NodePort (service.yaml에서 지정한 값)
        hostPort: 3000         # 외부에서 접속할 포트
        protocol: TCP
      - containerPort: 32001   # Prometheus의 NodePort (service.yaml에서 지정한 값)
        hostPort: 9090         # 외부에서 접속할 포트
        protocol: TCP
  - role: worker
    image: kindest/node:v1.29.7
  - role: worker
    image: kindest/node:v1.29.7
