{
 "title": "Disk I/O",
 "description": "graphs for disk operation",
 "tags": [
  "k8s",
  "storage"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_exporter_build_info{job=\"node-exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes - read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=\"node-exporter\", instance=~\"${instance:\\\\regex}\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Bytes - write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{job=\"node-exporter\",instance=~\"${instance:\\\\regex}\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "iOps - read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{job=\"node-exporter\",instance=~\"${instance:\\\\regex}\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "iOps - write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{job=\"node-exporter\",instance=~\"${instance:\\\\regex}\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Time - read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=\"node-exporter\",instance=~\"${instance:\\\\regex}\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Time - write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_write_time_seconds_total{job=\"node-exporter\",instance=~\"${instance:\\\\regex}\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Merged - read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_merged_total{job=\"node-exporter\",instance=~\"${instance:\\\\regex}\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Merged - write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_disk_writes_merged_total{job=\"node-exporter\",instance=~\"${instance:\\\\regex}\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}