{
 "title": "Viola Persistent Volume",
 "description": "Dashboard of Kubernetes / OpenShift volume information at cluster level as exported by Prometheus connected to Kubernetes / OpenShift.",
 "tags": [
  "k8s",
  "storage"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_OPENSHIFT_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pvc_percent_used_warning_threshold",
    "label": "PVC % Used Warning Threshold",
    "query": "80"
   }
  ]
 },
 "panels": [
  { "title": "Current Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bound PVCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (pv_collector_bound_pvc_count)) or vector(0)"
    }
   ]
  },
  {
   "title": "Unbound PVCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max (sum by (exported_namespace) (pv_collector_unbound_pvc_count))) or (vector(0))"
    }
   ]
  },
  {
   "title": "Running PVCs Above % Used Warning Threshold",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= ($pvc_percent_used_warning_threshold / 100)) or vector (0)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info{namespace=~\".*\", persistentvolumeclaim=~\".*\"} \n* on(namespace, persistentvolumeclaim)\ngroup_left()\n(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) \n/ max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes)) \n>= ($pvc_percent_used_warning_threshold / 100)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "PVC Stats",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info"
    },
    {
     "expr": "(1-max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info ) ) unless (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes )) or ((max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info ) ) and (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes )))"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes)"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes )"
    },
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes ))"
    }
   ]
  },
  { "title": "Use", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "All Running PVCs Used Bytes",
   "type": "timeseries",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ))",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Running PVCs % Used",
   "type": "timeseries",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) * 100",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  { "title": "Use Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Hourly Volume Use Rate",
   "type": "timeseries",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes [1h])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Daily Volume Use Rate",
   "type": "timeseries",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes [1d])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Weekly Volume Use Rate",
   "type": "timeseries",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes [1w])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  }
 ]
}