{
 "title": "Viola Monitoring - Kubernetes Components / ETCD",
 "tags": [
  "k8s",
  "components"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Kube-Apiserver",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Handles all API requests for the Kubernetes cluster. Metrics show request rates, response times, and errors to monitor performance."
   }
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "state가 UP인 Kube-apiserver의 합계",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"apiserver\"})"
    }
   ]
  },
  {
   "title": "Availability (7d) > 99.000%",
   "type": "stat",
   "description": "Kube-apiserver의 7일간의 요청 성공률 (가용성)\n(Kube-apiserver의 5xx을 제외한 모든 요청 수 / Kube-apiserver의 전체 요청 수)",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code!~\"5..\"}[7d])) /\nsum(rate(apiserver_request_total[7d]))"
    }
   ]
  },
  {
   "title": "ErrorBudgetDeviation (7d) > 99.000%",
   "type": "timeseries",
   "description": "Kube-apiserver의 7일간의 요청 성공룰과 목표 가용성(99.000%)의 오차\n{\bKube-apiserver의 7일간의 요청 성공률 - 목표 가용성}을 비율로 환산",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * ((sum(rate(apiserver_request_total{code!~\"5..\"}[7d])) / sum(rate(apiserver_request_total[7d]))) - 0.99)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Availability (7d)",
   "type": "stat",
   "description": "Kube-apiserver의 읽기 작업에 대한 요청 성공률\n(Kube-apiserver의  모든 읽기 요청 중 5xx을 제외한 수 / Kube-apiserver의  모든 읽기 요청 수)",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code!~\"5..\", verb=~\"GET|LIST|WATCH\"}[7d])) / sum(rate(apiserver_request_total{verb=~\"GET|LIST|WATCH\"}[7d]))"
    }
   ]
  },
  {
   "title": "Read SLI - Requests",
   "type": "timeseries",
   "description": "Kube-apiserver의 읽기 작업에 대한 응답 코드별 합계",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (code_resource:apiserver_request_total:rate5m{verb=\"read\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read SLI - Errors",
   "type": "timeseries",
   "description": "Kube-apiserver의 모든 읽기 작업 중 resource 별 5xx 코드의 합계",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"read\",code=~\"5..\"}) / sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"read\"})",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Read SLI - Duration",
   "type": "timeseries",
   "description": "Kube-apiserver에 대한 각 resource별 읽기 작업의 응답 소요 시간",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cluster_quantile:apiserver_request_sli_duration_seconds:histogram_quantile{verb=\"read\"}",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Write Availability (7d)",
   "type": "stat",
   "description": "Kube-apiserver의 쓰기 작업에 대한 요청 성공률\n(Kube-apiserver의  모든 쓰기 요청 중 5xx을 제외한 수 / Kube-apiserver의  모든 쓰기 요청 수)",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code!~\"5..\", verb=~\"POST|PUT|PATCH|DELETE\"}[7d])) /\nsum(rate(apiserver_request_total{verb=~\"POST|PUT|PATCH|DELETE\"}[7d]))"
    }
   ]
  },
  {
   "title": "Write SLI - Requests",
   "type": "timeseries",
   "description": "Kube-apiserver의 쓰기 작업에 대한 응답 코드별 합계",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (code_resource:apiserver_request_total:rate5m{verb=\"write\"})",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Write SLI - Errors",
   "type": "timeseries",
   "description": "Kube-apiserver의 모든 쓰기 작업 중 resource 별 5xx 코드의 합계",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"write\",code=~\"5..\"}) / sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"write\"})",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Write SLI - Duration",
   "type": "timeseries",
   "description": "Kube-apiserver에 대한 각 resource별 쓰기 작업의 응답 소요 시간",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cluster_quantile:apiserver_request_sli_duration_seconds:histogram_quantile{verb=\"write\"}",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Kube-Controller-Manager",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "Manages cluster state by running controllers (e.g., replicas). Metrics track how often tasks are reconciled and if there are delays."
   }
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "state가 UP인 Kube-\bcontroller-manager의 합계",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"kube-controller-manager\"})"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "description": "kube-controller-manager의 작업 queue에 resource별 작업이 추가되는 속도",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"kube-controller-manager\"}[$__rate_interval])) by (cluster, instance, name)",
     "legendFormat": "{{cluster}} {{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "timeseries",
   "description": "클러스터, 인스턴스, 작업대기열 이름, 히스토그램 버킷 별 kube-controller-manager의 work queue의 상위 99프로 작업의 최대 대기 시간\n(1초 이상일시 SLA 위반으로 판단)",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"kube-controller-manager\"}[$__rate_interval])) by (cluster, instance, name, le))",
     "legendFormat": "{{cluster}} {{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "description": "kube-apiserver의 응답 중 응답코드 별 합계 \n(2xx, 3xx, 4xx, 5xx)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\",code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\", code=~\"3..\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\", code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\", code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Kube-Scheduler",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 },
   "options": {
    "content": "Assigns pods to nodes based on resources and policies. Metrics include scheduling speed and failures."
   }
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "state가 UP인 Kube-\bscheduler의 합계",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"kube-scheduler\"})"
    }
   ]
  },
  {
   "title": "Scheduling Rate",
   "type": "timeseries",
   "description": "인스턴스별 kube scheduler의 pod shcduling 알고리즘 실행 비율",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_scheduling_algorithm_duration_seconds_count{job=\"kube-scheduler\"}[$__rate_interval])) by (cluster, instance)",
     "legendFormat": "{{cluster}} {{instance}} scheduling algorithm"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "description": "kube-apiserver의 응답 중 응답코드 별 합계 \n(2xx, 3xx, 4xx, 5xx)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-scheduler\", code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-scheduler\", code=~\"3..\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-scheduler\", code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-scheduler\", code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Kube-Proxy",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 60 },
   "options": {
    "content": "Controls networking between pods and services. Metrics track connection counts and rule synchronization."
   }
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "state가 UP인 Kube-\bproxy의 합계",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"kube-proxy\"})"
    }
   ]
  },
  {
   "title": "Rules Sync Rate",
   "type": "timeseries",
   "description": "초당 proxy 규칙 동기화 작업 실행 수",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubeproxy_sync_proxy_rules_duration_seconds_count{job=\"kube-proxy\"}[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Rules Sync Latency 99th Quantile",
   "type": "timeseries",
   "description": "인스턴스별 초당 proxy 규칙 동기화 작업 실행 시 소요시간 수 (상위 99% 작업)",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(kubeproxy_sync_proxy_rules_duration_seconds_bucket{job=\"kube-proxy\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Programming Rate",
   "type": "timeseries",
   "description": "초당 network programming 작업 실행 횟수",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubeproxy_network_programming_duration_seconds_count{job=\"kube-proxy\"}[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "description": "kube-apiserver의 응답 중 응답코드 별 합계\n(2xx, 3xx, 4xx, 5xx)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-proxy\",code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-proxy\",code=~\"3..\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-proxy\",code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-proxy\",code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "ETCD",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 78 },
   "options": {
    "content": "Stores all cluster data in a distributed database. Metrics show response times, and synchronization."
   }
  },
  {
   "title": "ETCD Request Rate (5m)",
   "type": "timeseries",
   "description": "ETCD 서버에서 발생한 요청 수의 초당 증가율 중 5분동안의 평균값",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    { "expr": "rate(etcd_requests_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ETCD Request Error Rate (5m)",
   "type": "timeseries",
   "description": "ETCD 서버에서 발생한 요청 수의 초당 증가율 대비 오류 응답수의 비율의 5분동안의 평균 값",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "rate(etcd_request_errors_total[5m]) / rate(etcd_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD Bookmark Rate",
   "type": "timeseries",
   "description": "ETCD에서 워치(watch) 스트림의 북마크 이벤트 발생 횟수의 5분동안의 평균값\n(북마크: client의 watch 작업시 발생하는 이벤트)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum(rate(etcd_bookmark_counts[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}