prometheus:
  image:
    repository: quay.io/prometheus/prometheus
    tag: v2.55.1
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 2Gi
  storageSpec:
    volumeClaimTemplate:
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
        storageClassName: { { .Values.storageClass.name } }  # storageClassName 연결

  # etcd 인증서가 이미 monitoring 네임스페이스에 secret으로 생성되어 있다고 가정
  additionalScrapeConfigs: |
    - job_name: 'kube-etcd'
      kubernetes_sd_configs:
        - role: node
      scheme: https
      tls_config:
        ca_file: /etc/prometheus/secrets/etcd-client-cert/etcd-ca
        cert_file: /etc/prometheus/secrets/etcd-client-cert/etcd-client
        key_file: /etc/prometheus/secrets/etcd-client-cert/etcd-client-key
      relabel_configs:
        - source_labels: [__address__]
          action: replace
          target_label: __address__
          regex: ([^:]+):\d+
          replacement: ${1}:2379

  # 컨트롤러 컴포넌트 메트릭 (kube-scheduler, kube-controller-manager)
  additionalScrapeConfigsController: |
    - job_name: 'kube-scheduler'
      static_configs:
        - targets: ['localhost:10251']
    - job_name: 'kube-controller-manager'
      static_configs:
        - targets: ['localhost:10257']

prometheusOperator:
  prometheusSpec:
    additionalScrapeConfigsSecret: additional-scrape-configs

storageClass:
  name: "local-path"
  provisioner: "rancher.io/local-path"
