apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-grafana-datasource
  labels:
    grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "monitoring-stack.fullname" . }}-prometheus:9090
        isDefault: true
        editable: false
