apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-loki
spec:
  serviceName: {{ include "monitoring-stack.fullname" . }}-loki
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "monitoring-stack.fullname" . }}-loki
  template:
    metadata:
      labels:
        app: {{ include "monitoring-stack.fullname" . }}-loki
    spec:
      containers:
        - name: loki
          image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: storage
              mountPath: /loki
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "{{ .Values.loki.persistence.size }}"
