apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: "{{ .Values.prometheus_node_exporter.image.repository }}:{{ .Values.prometheus_node_exporter.image.tag }}"
          ports:
            - containerPort: 9100
