apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-prometheus
spec:
  serviceName: {{ include "monitoring-stack.fullname" . }}-prometheus
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "monitoring-stack.fullname" . }}-prometheus
  template:
    metadata:
      labels:
        app: {{ include "monitoring-stack.fullname" . }}-prometheus
    spec:
      serviceAccountName: {{ include "monitoring-stack.fullname" . }}-prometheus
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          args:
            - --config.file=/etc/prometheus/prometheus.yml
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: {{ include "monitoring-stack.fullname" . }}-prometheus-config
