apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-promtail-config
data:
  promtail.yaml: |-
    server:
      http_listen_port: 9080
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: "http://{{ include "monitoring-stack.fullname" . }}-loki:3100/loki/api/v1/push"
    scrape_configs:
      - job_name: system
        static_configs:
          - targets: ["localhost"]
            labels:
              job: varlogs
              __path__: /var/log/*.log
