apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
{{- if .Values.prometheus.additionalScrapeConfigs }}
{{ .Values.prometheus.additionalScrapeConfigs | indent 6 }}
{{- else }}
      - job_name: 'kube-controller'
        static_configs:
          - targets: ['<kube-apiserver-host>:6443', '<kube-controller-manager-host>:10257', '<kube-scheduler-host>:10259']
      - job_name: 'etcd'
        static_configs:
          - targets: ['<etcd-host>:2379']
      - job_name: 'kubelet'
        static_configs:
          - targets: ['<node-ip>:10250']
      - job_name: 'cilium'
        static_configs:
          - targets: ['<cilium-agent-ip>:9090']
{{- end }}
