apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-prometheus
  labels:
    app: {{ include "monitoring-stack.fullname" . }}-prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-prometheus
rules:
  - apiGroups: [ "" ]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups: [ "extensions", "apps" ]
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs: [ "/metrics" ]
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "monitoring-stack.fullname" . }}-prometheus
subjects:
  - kind: ServiceAccount
    name: {{ include "monitoring-stack.fullname" . }}-prometheus
    namespace: default
