apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-promtail
spec:
  selector:
    matchLabels:
      app: {{ include "monitoring-stack.fullname" . }}-promtail
  template:
    metadata:
      labels:
        app: {{ include "monitoring-stack.fullname" . }}-promtail
    spec:
      containers:
        - name: promtail
          image: "{{ .Values.promtail.image.repository }}:{{ .Values.promtail.image.tag }}"
          args:
            - -config.file=/etc/promtail/promtail.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "monitoring-stack.fullname" . }}-promtail-config
