apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-prometheus
spec:
  selector:
    app: {{ include "monitoring-stack.fullname" . }}-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 32001
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-grafana
spec:
  selector:
    app: {{ include "monitoring-stack.fullname" . }}-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-node-exporter
spec:
  selector:
    app: {{ include "monitoring-stack.fullname" . }}-node-exporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
  type: ClusterIP
