apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-hostpath
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/grafana   # 호스트 머신의 실제 경로
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""   # hostPath PV는 StorageClass 없이 사용
