apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: <NFS-서버-IP>   # NFS 서버 IP
    path: /exported/path    # NFS 서버에서 공유하는 경로
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""   # NFS PV는 StorageClass 없이 사용하거나 별도 지정
