alertmanager:
  enabled: true

grafana:
  enabled: true
  defaultDashboardsTimezone: Asia/Seoul
  adminPassword: admin1234
  persistence:
    enabled: true
    storageClass: "standard"   # 동적 프로비저닝 환경: 클러스터에 존재하는 StorageClass 이름. 동적 프로비저닝이 안되는 경우 수동 PV 예시 참고.
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  additionalDataSources:
    - name: Thanos
      type: prometheus
      access: proxy
      url: http://172.21.0.2:30091   # mgmt 클러스터의 Thanos Query 외부 접근 주소 (NodePort 또는 Ingress)
      isDefault: false
      editable: true

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 5d
    retentionSize: "10GiB"
    scrapeInterval: "15s"
  externalLabels:
    cluster: mgmt
