objstoreConfig: |-
  type: s3
  config:
    bucket: thanos
    endpoint: 172.21.0.14:32000   # 실제 minio 클러스터의 외부 IP와 포트로 수정
    access_key: admin
    secret_key: admin1234
    insecure: true
    signature_version2: true

query:
  enabled: true
  # biz 클러스터의 프로메테우스가 배포되어있는 Node IP (Prometheus 사이드카가 외부에 노출된 Node IP)
  stores:
    - 172.21.0.6:31000   # biz1 클러스터: Prometheus 사이드카가 노출된 Node IP (예: biz1-control-plane)
    - 172.21.0.7:31000   # biz1 클러스터: 추가 Prometheus 노드 IP (필요 시 단일 주소만 사용)
    - 172.21.0.8:31000   # biz2 클러스터: Prometheus 사이드카가 노출된 Node IP (예: biz2-control-plane)
    - 172.21.0.10:31000  # biz2 클러스터: 추가 Prometheus 노드 IP (필요 시 단일 주소만 사용)
    - 172.21.0.11:31000  # biz2 클러스터: 추가 Prometheus 노드 IP (필요 시 단일 주소만 사용)
    - 172.21.0.12:31000  # biz2 클러스터: 추가 Prometheus 노드 IP (필요 시 단일 주소만 사용)
    - thanos-storegateway.monitoring.svc.cluster.local:10901  # mgmt 클러스터 내부 Store Gateway
  replicaCount: 2
  service:
    type: NodePort
    nodePorts:
      grpc: 30901
      http: 30902
  replicaLabel: prometheus_replica

bucketweb:
  enabled: true

compactor:
  enabled: true

storegateway:
  enabled: true

ruler:
  enabled: true
  alertmanagers:
    - http://alertmanager.monitoring.svc.cluster.local:9093
  config: |-
    groups:
    - name: default
      rules: []
